import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { VehiclesRepository } from './vehicles.repository.js';
import { VehiclesAuthorizationPolicy, type VehiclesAuthorizationContext } from './vehicles.policy.js';
import { isUuid, isVehicleStatus, parseIdentifier, type CreateVehicleInput, type UpdateVehicleInput } from './vehicles.types.js';

function keys(body: Record<string, unknown>, allowed: readonly string[]): void { if (Object.keys(body).some((key) => !allowed.includes(key))) throw new BadRequestException(); }
function createInput(body: unknown): CreateVehicleInput { const value = (body ?? {}) as Record<string, unknown>; keys(value, ['tenant_id', 'identifier']); if (!isUuid(value.tenant_id)) throw new BadRequestException(); return { tenantId: value.tenant_id, identifier: parseIdentifier(value.identifier) }; }
function updateInput(body: unknown): UpdateVehicleInput { const value = (body ?? {}) as Record<string, unknown>; keys(value, ['status', 'version']); if (!Number.isInteger(value.version) || Number(value.version) < 1 || !isVehicleStatus(value.status)) throw new BadRequestException(); return { status: value.status, version: Number(value.version) }; }
function persist<T>(operation: () => Promise<T>): Promise<T> { return operation().catch((e: unknown) => { const code = (e as { code?: string }).code; if (code === 'AUTHORITY_REVOKED' || code === 'VEHICLE_VERSION_CONFLICT') throw new ConflictException(); if (code === 'TENANT_LIFECYCLE_DENIED') throw new NotFoundException(); if (code === '23505') throw new ConflictException(); if (code === '23503' || code === '23514') throw new BadRequestException(); throw e; }); }

@Injectable()
export class VehiclesService {
  constructor(private readonly repository: VehiclesRepository, private readonly policy: VehiclesAuthorizationPolicy) {}
  async create(context: VehiclesAuthorizationContext, body: unknown) { const input = createInput(body); if (!this.policy.canManage(context, input.tenantId)) throw new NotFoundException(); return persist(() => this.repository.create(input, { actorId: context.principal.subject, correlationId: context.correlationId, requiredRoles: ['school-admin', 'super-admin'] })); }
  async list(context: VehiclesAuthorizationContext, tenantId?: string) { if (tenantId && !isUuid(tenantId)) throw new BadRequestException(); if (!this.policy.isSuperAdmin(context) && (!context.principal.tenantId || (tenantId && tenantId !== context.principal.tenantId))) throw new NotFoundException(); const rows = await this.repository.list(this.policy.isSuperAdmin(context) ? tenantId : context.principal.tenantId); if (rows.length && !this.policy.canRead(context, rows[0]!.tenantId)) throw new NotFoundException(); return rows; }
  async get(context: VehiclesAuthorizationContext, id: string) { if (!isUuid(id)) throw new NotFoundException(); const row = await this.repository.get(id, this.policy.isSuperAdmin(context) ? undefined : context.principal.tenantId); if (!row || !this.policy.canRead(context, row.tenantId)) throw new NotFoundException(); return row; }
  async update(context: VehiclesAuthorizationContext, id: string, body: unknown) { if (!isUuid(id)) throw new NotFoundException(); const current = await this.repository.get(id, this.policy.isSuperAdmin(context) ? undefined : context.principal.tenantId); if (!current || !this.policy.canManage(context, current.tenantId)) throw new NotFoundException(); return persist(async () => { const result = await this.repository.update(id, updateInput(body), { actorId: context.principal.subject, correlationId: context.correlationId, requiredRoles: ['school-admin', 'super-admin'] }); if (!result) throw Object.assign(new Error('VEHICLE_VERSION_CONFLICT'), { code: 'VEHICLE_VERSION_CONFLICT' }); return result; }); }
}
