import { BadRequestException, ConflictException, Injectable, NotFoundException, UnauthorizedException } from '@nestjs/common';
import { ParentsRepository } from './parents.repository.js';
import { ParentsAuthorizationPolicy, type ParentsAuthorizationContext } from './parents.policy.js';
import { isParentStatus, isUuid, type CreateParentInput, type CreateRelationshipInput, type UpdateParentInput } from './parents.types.js';
function keys(v: Record<string,unknown>, allowed: readonly string[]): void { if(Object.keys(v).some(k=>!allowed.includes(k))) throw new BadRequestException(); }
function createParent(body:unknown):CreateParentInput{const v=(body??{}) as Record<string,unknown>;keys(v,['tenant_id','user_id']);if(!isUuid(v.tenant_id)||!isUuid(v.user_id))throw new BadRequestException();return{tenantId:v.tenant_id,userId:v.user_id};}
function updateParent(body:unknown):UpdateParentInput{const v=(body??{}) as Record<string,unknown>;keys(v,['status','version']);if(!Number.isInteger(v.version)||Number(v.version)<1||!isParentStatus(v.status))throw new BadRequestException();return{status:v.status,version:Number(v.version)};}
function link(body:unknown):CreateRelationshipInput{const v=(body??{}) as Record<string,unknown>;keys(v,['student_id','guardian_id']);if(!isUuid(v.student_id)||!isUuid(v.guardian_id))throw new BadRequestException();return{studentId:v.student_id,guardianId:v.guardian_id};}
function version(body:unknown):number{const v=(body??{}) as Record<string,unknown>;keys(v,['version']);if(!Number.isInteger(v.version)||Number(v.version)<1)throw new BadRequestException();return Number(v.version);}
function persist<T>(fn:()=>Promise<T>):Promise<T>{return fn().catch((e:unknown)=>{const c=(e as{code?:string}).code;if(c==='AUTHORITY_REVOKED')throw new UnauthorizedException();if(['TENANT_LIFECYCLE_DENIED','USER_NOT_ACTIVE','RELATIONSHIP_TARGET_NOT_FOUND','LIFECYCLE_DENIED'].includes(c??''))throw new NotFoundException();if(c==='23505'||c==='RELATIONSHIP_VERSION_CONFLICT')throw new ConflictException();throw e;});}
@Injectable()
export class ParentsService {
  constructor(private readonly repo:ParentsRepository,private readonly policy:ParentsAuthorizationPolicy){}
  async create(c:ParentsAuthorizationContext,b:unknown){const i=createParent(b);if(!this.policy.canManage(c,i.tenantId))throw new NotFoundException();return persist(()=>this.repo.create(i,{actorId:c.principal.subject,correlationId:c.correlationId,requiredRoles:['school-admin','super-admin']}));}
  async list(c:ParentsAuthorizationContext,tenantId?:string){if(tenantId&&!isUuid(tenantId))throw new BadRequestException();if(!this.policy.isSuperAdmin(c)&&(!tenantId||tenantId!==c.principal.tenantId))throw new NotFoundException();return this.repo.list(this.policy.isSuperAdmin(c)?tenantId:c.principal.tenantId);}
  async get(c:ParentsAuthorizationContext,id:string){if(!isUuid(id))throw new NotFoundException();const p=await this.repo.get(id,this.policy.isSuperAdmin(c)?undefined:c.principal.tenantId);if(!p||!this.policy.canReadManaged(c,p.tenantId))throw new NotFoundException();return p;}
  async update(c:ParentsAuthorizationContext,id:string,b:unknown){if(!isUuid(id))throw new NotFoundException();const p=await this.repo.get(id,this.policy.isSuperAdmin(c)?undefined:c.principal.tenantId);if(!p||!this.policy.canManage(c,p.tenantId))throw new NotFoundException();return persist(()=>this.repo.update(id,updateParent(b),{actorId:c.principal.subject,correlationId:c.correlationId,requiredRoles:['school-admin','super-admin']}));}
  async link(c:ParentsAuthorizationContext,b:unknown){if(!this.policy.isSchoolAdmin(c)&&!this.policy.isSuperAdmin(c))throw new NotFoundException();return persist(()=>this.repo.link(link(b),{actorId:c.principal.subject,correlationId:c.correlationId,requiredRoles:['school-admin','super-admin']}));}
  async unlink(c:ParentsAuthorizationContext,id:string,b:unknown){if(!isUuid(id)||(!this.policy.isSchoolAdmin(c)&&!this.policy.isSuperAdmin(c)))throw new NotFoundException();return persist(async()=>{const out=await this.repo.unlink(id,version(b),{actorId:c.principal.subject,correlationId:c.correlationId,requiredRoles:['school-admin','super-admin']});if(!out)throw Object.assign(new Error('RELATIONSHIP_VERSION_CONFLICT'),{code:'RELATIONSHIP_VERSION_CONFLICT'});return out;});}
  async children(c:ParentsAuthorizationContext){if(!this.policy.isParent(c)||!isUuid(c.principal.subject))throw new NotFoundException();return this.repo.children(c.principal.subject);}
}
