import { Inject, Injectable, OnModuleDestroy } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import type { Pool, PoolClient } from 'pg';
import type { CreateParentInput, CreateRelationshipInput, ParentRecord, RelationshipRecord, UpdateParentInput } from './parents.types.js';
export const PARENTS_DB = Symbol('PARENTS_DB');
export interface ParentAuditContext { readonly actorId: string; readonly correlationId: string; readonly requiredRoles?: readonly string[]; }
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function err(code: string): Error { const e = new Error(code); Object.assign(e, { code }); return e; }
type ParentRow = { id: string; tenant_id: string; user_id: string; status: 'active' | 'archived'; version: number; created_at: Date; updated_at: Date };
type RelationshipRow = { id: string; tenant_id: string; school_id: string; student_id: string; guardian_id: string; status: 'active' | 'revoked'; version: number };
function parent(row: ParentRow): ParentRecord { return { id: row.id, tenantId: row.tenant_id, userId: row.user_id, status: row.status, version: row.version, createdAt: row.created_at.toISOString(), updatedAt: row.updated_at.toISOString() }; }
function rel(row: RelationshipRow): RelationshipRecord { return { id: row.id, tenantId: row.tenant_id, schoolId: row.school_id, studentId: row.student_id, guardianId: row.guardian_id, status: row.status, version: row.version }; }
@Injectable()
export class ParentsRepository implements OnModuleDestroy {
  constructor(@Inject(PARENTS_DB) private readonly pool: Pool) {}
  private async authority(client: PoolClient, actorId: string, tenantId: string, roles: readonly string[]): Promise<void> {
    if (!UUID.test(actorId)) throw err('AUTHORITY_REVOKED');
    const r = await client.query(`SELECT r.role FROM "user" u JOIN tenant_membership m ON m.user_id=u.id AND m.status='active' JOIN role_assignment r ON r.membership_id=m.id AND r.status='active' JOIN tenant t ON t.id=m.tenant_id AND t.status='active' WHERE u.id=$1 AND u.status='active' AND (m.tenant_id=$2 OR r.role='super-admin') AND r.role=ANY($3::text[]) FOR UPDATE OF u,m,r,t`, [actorId, tenantId, roles]);
    if (!r.rows.length) throw err('AUTHORITY_REVOKED');
  }
  private async audit(client: PoolClient, c: ParentAuditContext, tenantId: string, targetId: string, action: string): Promise<void> { await client.query('INSERT INTO audit_record (id,tenant_id,actor_id,actor_type,action,target_type,target_id,outcome,correlation_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)', [randomUUID(), tenantId, c.actorId, 'human', action, 'guardian', targetId, 'committed', c.correlationId]); }
  async create(input: CreateParentInput, c: ParentAuditContext): Promise<ParentRecord> { const client=await this.pool.connect(); try { await client.query('BEGIN'); const t=await client.query<{ status: string }>('SELECT status FROM tenant WHERE id=$1 FOR UPDATE',[input.tenantId]); if(!t.rows[0]||t.rows[0].status!=='active') throw err('TENANT_LIFECYCLE_DENIED'); await this.authority(client,c.actorId,input.tenantId,c.requiredRoles??['school-admin','super-admin']); const u=await client.query<{ id: string }>(`SELECT u.id FROM "user" u JOIN tenant_membership m ON m.user_id=u.id AND m.tenant_id=$2 AND m.status='active' JOIN role_assignment ra ON ra.membership_id=m.id AND ra.role='parent' AND ra.status='active' WHERE u.id=$1 AND u.status='active'`,[input.userId,input.tenantId]); if(!u.rows[0]) throw err('USER_NOT_ACTIVE'); const r=await client.query<ParentRow>('INSERT INTO guardian(id,tenant_id,user_id) VALUES($1,$2,$3) RETURNING *',[randomUUID(),input.tenantId,input.userId]); await this.audit(client,c,input.tenantId,r.rows[0]!.id,'guardian.create'); await client.query('COMMIT'); return parent(r.rows[0]!); } catch(e){await client.query('ROLLBACK');throw e;} finally{client.release();} }
  async list(tenantId?: string): Promise<ParentRecord[]> { const r=await this.pool.query<ParentRow>('SELECT id,tenant_id,user_id,status,version,created_at,updated_at FROM guardian WHERE ($1::uuid IS NULL OR tenant_id=$1) AND status=\'active\' ORDER BY id',[tenantId??null]); return r.rows.map(parent); }
  async get(id: string, tenantId?: string): Promise<ParentRecord|null> { const r=await this.pool.query<ParentRow>('SELECT id,tenant_id,user_id,status,version,created_at,updated_at FROM guardian WHERE id=$1 AND ($2::uuid IS NULL OR tenant_id=$2) AND status=\'active\'',[id,tenantId??null]); return r.rows[0]?parent(r.rows[0]):null; }
  async update(id:string,input:UpdateParentInput,c:ParentAuditContext):Promise<ParentRecord|null>{const client=await this.pool.connect();try{await client.query('BEGIN');const cur=await client.query<{tenant_id:string}>('SELECT tenant_id FROM guardian WHERE id=$1 FOR UPDATE',[id]);if(!cur.rows[0]){await client.query('ROLLBACK');return null;}await this.authority(client,c.actorId,cur.rows[0].tenant_id,c.requiredRoles??['school-admin','super-admin']);const r=await client.query<ParentRow>('UPDATE guardian SET status=COALESCE($2,status),version=version+1,updated_at=NOW() WHERE id=$1 AND version=$3 RETURNING *',[id,input.status??null,input.version]);if(!r.rows[0]){await client.query('ROLLBACK');return null;}await this.audit(client,c,cur.rows[0].tenant_id,id,'guardian.update');await client.query('COMMIT');return parent(r.rows[0]);}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
  async link(input:CreateRelationshipInput,c:ParentAuditContext):Promise<RelationshipRecord>{const client=await this.pool.connect();try{await client.query('BEGIN');const r=await client.query<Pick<RelationshipRow,'tenant_id'|'school_id'>>('SELECT g.tenant_id,s.school_id FROM guardian g JOIN student s ON s.tenant_id=g.tenant_id WHERE g.id=$1 AND g.status=\'active\' AND s.id=$2 AND s.status=\'active\' FOR UPDATE OF g,s',[input.guardianId,input.studentId]);if(!r.rows[0])throw err('RELATIONSHIP_TARGET_NOT_FOUND');const row=r.rows[0];const t=await client.query<{status:string}>('SELECT status FROM tenant WHERE id=$1 FOR UPDATE',[row.tenant_id]);const sc=await client.query<{status:string}>('SELECT status FROM school WHERE id=$1 AND tenant_id=$2 FOR UPDATE',[row.school_id,row.tenant_id]);if(t.rows[0]?.status!=='active'||sc.rows[0]?.status!=='active')throw err('LIFECYCLE_DENIED');await this.authority(client,c.actorId,row.tenant_id,c.requiredRoles??['school-admin','super-admin']);const out=await client.query<RelationshipRow>('INSERT INTO student_guardian_relationship(id,tenant_id,school_id,student_id,guardian_id) VALUES($1,$2,$3,$4,$5) RETURNING *',[randomUUID(),row.tenant_id,row.school_id,input.studentId,input.guardianId]);await this.audit(client,c,row.tenant_id,out.rows[0]!.id,'guardian.link');await client.query('COMMIT');return rel(out.rows[0]!);}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
  async unlink(id:string,version:number,c:ParentAuditContext):Promise<RelationshipRecord|null>{const client=await this.pool.connect();try{await client.query('BEGIN');const cur=await client.query<RelationshipRow>('SELECT * FROM student_guardian_relationship WHERE id=$1 FOR UPDATE',[id]);if(!cur.rows[0]){await client.query('ROLLBACK');return null;}const row=cur.rows[0];await this.authority(client,c.actorId,row.tenant_id,c.requiredRoles??['school-admin','super-admin']);const out=await client.query<RelationshipRow>("UPDATE student_guardian_relationship SET status='revoked',version=version+1,updated_at=NOW() WHERE id=$1 AND version=$2 AND status='active' RETURNING *",[id,version]);if(!out.rows[0]){await client.query('ROLLBACK');return null;}await this.audit(client,c,row.tenant_id,id,'guardian.unlink');await client.query('COMMIT');return rel(out.rows[0]!);}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
  async children(userId:string):Promise<Array<Record<string,unknown>>>{const r=await this.pool.query(`SELECT s.id AS student_id,s.tenant_id,s.school_id,s.display_name,s.status,r.id AS relationship_id FROM guardian g JOIN student_guardian_relationship r ON r.guardian_id=g.id AND r.status='active' JOIN student s ON s.id=r.student_id AND s.status='active' JOIN tenant t ON t.id=s.tenant_id AND t.status='active' JOIN school sc ON sc.id=s.school_id AND sc.status='active' WHERE g.user_id=$1 AND g.status='active'`,[userId]);return r.rows;}
  async onModuleDestroy():Promise<void>{await this.pool.end();}
}
