import { Inject, Injectable, OnModuleDestroy } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import type { Pool, PoolClient } from 'pg';
import type { CreateTransportServiceInput, TransportServiceRecord, TransportServiceStatus, UpdateTransportServiceInput } from './services.types.js';
export const SERVICES_DB = Symbol('SERVICES_DB');
export interface ServicesAuditContext { readonly actorId: string; readonly correlationId: string; readonly requiredRoles?: readonly string[]; }
type ServiceRow = { id: string; tenant_id: string; school_id: string; route_id: string; name: string; status: TransportServiceStatus; version: number; created_at: Date; updated_at: Date };
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function error(code: string): Error { const e = new Error(code); Object.assign(e, { code }); return e; }
function fromRow(row: ServiceRow): TransportServiceRecord { return { id: row.id, tenantId: row.tenant_id, schoolId: row.school_id, routeId: row.route_id, name: row.name, status: row.status, version: row.version, createdAt: row.created_at.toISOString(), updatedAt: row.updated_at.toISOString() }; }
@Injectable()
export class ServicesRepository implements OnModuleDestroy {
  constructor(@Inject(SERVICES_DB) private readonly pool: Pool) {}
  private async lockAuthority(client: PoolClient, actorId: string, tenantId: string, roles: readonly string[]): Promise<void> { if (!UUID.test(actorId)) throw error('AUTHORITY_REVOKED'); const result = await client.query(`SELECT r.role FROM "user" u JOIN tenant_membership m ON m.user_id = u.id AND m.status = 'active' JOIN role_assignment r ON r.membership_id = m.id AND r.status = 'active' JOIN tenant t ON t.id = m.tenant_id AND t.status = 'active' WHERE u.id = $1 AND u.status = 'active' AND (m.tenant_id = $2 OR r.role = 'super-admin') AND r.role = ANY($3::text[]) FOR UPDATE OF u, m, r, t`, [actorId, tenantId, roles]); if (!result.rows.length) throw error('AUTHORITY_REVOKED'); }
  async assertReadAuthority(actorId: string, tenantId: string): Promise<void> { const client = await this.pool.connect(); try { await client.query('BEGIN'); await this.lockAuthority(client, actorId, tenantId, ['school-admin', 'school-operator', 'super-admin']); await client.query('COMMIT'); } catch (e) { await client.query('ROLLBACK'); throw e; } finally { client.release(); } }
  private async audit(client: PoolClient, context: ServicesAuditContext, tenantId: string, targetId: string, action: string): Promise<void> { await client.query('INSERT INTO audit_record (id, tenant_id, actor_id, actor_type, action, target_type, target_id, outcome, correlation_id) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)', [randomUUID(), tenantId, context.actorId, 'human', action, 'transport_service', targetId, 'committed', context.correlationId]); }
  async getSchoolContext(schoolId: string): Promise<{ tenantId: string; status: string; tenantStatus: string } | null> { const result = await this.pool.query<{ tenant_id: string; status: string; tenant_status: string }>('SELECT sc.tenant_id, sc.status, t.status AS tenant_status FROM school sc JOIN tenant t ON t.id = sc.tenant_id WHERE sc.id = $1', [schoolId]); return result.rows[0] ? { tenantId: result.rows[0].tenant_id, status: result.rows[0].status, tenantStatus: result.rows[0].tenant_status } : null; }
  async create(input: CreateTransportServiceInput, context: ServicesAuditContext): Promise<TransportServiceRecord> {
    const client = await this.pool.connect();
    try {
      await client.query('BEGIN');
      const scope = await client.query<{ tenant_id: string; school_status: string; tenant_status: string; route_status: TransportServiceStatus }>(
        `SELECT sc.tenant_id, sc.status AS school_status, t.status AS tenant_status, r.status AS route_status
         FROM school sc JOIN tenant t ON t.id = sc.tenant_id
         JOIN route r ON r.id = $2 AND r.school_id = sc.id AND r.tenant_id = sc.tenant_id
         WHERE sc.id = $1 FOR UPDATE OF sc, t, r`, [input.schoolId, input.routeId]);
      if (!scope.rows[0] || scope.rows[0].school_status !== 'active') throw error('SCHOOL_LIFECYCLE_DENIED');
      if (scope.rows[0].tenant_status !== 'active') throw error('TENANT_LIFECYCLE_DENIED');
      if (scope.rows[0].route_status !== 'active') throw error('ROUTE_LIFECYCLE_DENIED');
      await this.lockAuthority(client, context.actorId, scope.rows[0].tenant_id, context.requiredRoles ?? ['school-admin', 'super-admin']);
      const result = await client.query<ServiceRow>('INSERT INTO transport_service (id, tenant_id, school_id, route_id, name) VALUES ($1, $2, $3, $4, $5) RETURNING id, tenant_id, school_id, route_id, name, status, version, created_at, updated_at', [randomUUID(), scope.rows[0].tenant_id, input.schoolId, input.routeId, input.name]);
      await this.audit(client, context, scope.rows[0].tenant_id, result.rows[0]!.id, 'transport_service.create');
      await client.query('COMMIT');
      return fromRow(result.rows[0]!);
    } catch (e) { await client.query('ROLLBACK'); throw e; } finally { client.release(); }
  }
  async list(schoolId: string, tenantId?: string): Promise<TransportServiceRecord[]> { const result = await this.pool.query<ServiceRow>(`SELECT s.id, s.tenant_id, s.school_id, s.route_id, s.name, s.status, s.version, s.created_at, s.updated_at FROM transport_service s JOIN school sc ON sc.id = s.school_id AND sc.tenant_id = s.tenant_id AND sc.status = 'active' JOIN tenant t ON t.id = s.tenant_id AND t.status = 'active' JOIN route r ON r.id = s.route_id AND r.tenant_id = s.tenant_id AND r.school_id = s.school_id AND r.status = 'active' WHERE s.school_id = $1 AND s.status = 'active' AND ($2::uuid IS NULL OR s.tenant_id = $2) ORDER BY s.id`, [schoolId, tenantId ?? null]); return result.rows.map(fromRow); }
  async get(id: string, schoolId: string, tenantId?: string): Promise<TransportServiceRecord | null> { const result = await this.pool.query<ServiceRow>(`SELECT s.id, s.tenant_id, s.school_id, s.route_id, s.name, s.status, s.version, s.created_at, s.updated_at FROM transport_service s JOIN school sc ON sc.id = s.school_id AND sc.tenant_id = s.tenant_id AND sc.status = 'active' JOIN tenant t ON t.id = s.tenant_id AND t.status = 'active' JOIN route r ON r.id = s.route_id AND r.tenant_id = s.tenant_id AND r.school_id = s.school_id AND r.status = 'active' WHERE s.id = $1 AND s.school_id = $2 AND s.status = 'active' AND ($3::uuid IS NULL OR s.tenant_id = $3)`, [id, schoolId, tenantId ?? null]); return result.rows[0] ? fromRow(result.rows[0]) : null; }
  async update(id: string, schoolId: string, input: UpdateTransportServiceInput, context: ServicesAuditContext): Promise<TransportServiceRecord | null> { const client = await this.pool.connect(); try { await client.query('BEGIN'); const current = await client.query<{ tenant_id: string; service_status: TransportServiceStatus; school_status: string; tenant_status: string; route_status: string }>('SELECT s.tenant_id, s.status AS service_status, sc.status AS school_status, t.status AS tenant_status, r.status AS route_status FROM transport_service s JOIN school sc ON sc.id = s.school_id AND sc.tenant_id = s.tenant_id JOIN tenant t ON t.id = s.tenant_id JOIN route r ON r.id = s.route_id AND r.tenant_id = s.tenant_id AND r.school_id = s.school_id WHERE s.id = $1 AND s.school_id = $2 FOR UPDATE OF s, sc, t, r', [id, schoolId]); if (!current.rows[0]) { await client.query('ROLLBACK'); return null; } if (current.rows[0].school_status !== 'active') throw error('SCHOOL_LIFECYCLE_DENIED'); if (current.rows[0].tenant_status !== 'active') throw error('TENANT_LIFECYCLE_DENIED'); if (current.rows[0].route_status !== 'active') throw error('ROUTE_LIFECYCLE_DENIED'); if (current.rows[0].service_status !== 'active') throw error('SERVICE_LIFECYCLE_DENIED'); await this.lockAuthority(client, context.actorId, current.rows[0].tenant_id, context.requiredRoles ?? ['school-admin', 'super-admin']); const result = await client.query<ServiceRow>('UPDATE transport_service SET name = COALESCE($3, name), status = COALESCE($4, status), version = version + 1, updated_at = NOW() WHERE id = $1 AND school_id = $2 AND status = \'active\' AND version = $5 RETURNING id, tenant_id, school_id, route_id, name, status, version, created_at, updated_at', [id, schoolId, input.name ?? null, input.status ?? null, input.version]); if (!result.rows[0]) { await client.query('ROLLBACK'); return null; } await this.audit(client, context, current.rows[0].tenant_id, id, 'transport_service.update'); await client.query('COMMIT'); return fromRow(result.rows[0]); } catch (e) { await client.query('ROLLBACK'); throw e; } finally { client.release(); } }
  async onModuleDestroy(): Promise<void> { await this.pool.end(); }
}
