import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { ServicesRepository } from './services.repository.js';
import { ServicesAuthorizationPolicy, type ServicesAuthorizationContext } from './services.policy.js';
import { isTransportServiceStatus, isUuid, validateTransportServiceName, type CreateTransportServiceInput, type UpdateTransportServiceInput } from './services.types.js';
function keys(body: Record<string, unknown>, allowed: readonly string[]): void { if (Object.keys(body).some((key) => !allowed.includes(key))) throw new BadRequestException(); }
function parseCreate(body: unknown): CreateTransportServiceInput { const value = (body ?? {}) as Record<string, unknown>; keys(value, ['school_id', 'route_id', 'name']); if (!isUuid(value.school_id) || !isUuid(value.route_id)) throw new BadRequestException(); return { schoolId: value.school_id, routeId: value.route_id, name: validateTransportServiceName(value.name) }; }
function parseUpdate(body: unknown): UpdateTransportServiceInput { const value = (body ?? {}) as Record<string, unknown>; keys(value, ['name', 'status', 'version']); if (!Number.isInteger(value.version) || Number(value.version) < 1 || (value.name === undefined && value.status === undefined)) throw new BadRequestException(); if (value.status !== undefined && !isTransportServiceStatus(value.status)) throw new BadRequestException(); return { name: value.name === undefined ? undefined : validateTransportServiceName(value.name), status: value.status as UpdateTransportServiceInput['status'], version: Number(value.version) }; }
function persist<T>(operation: () => Promise<T>): Promise<T> { return operation().catch((e: unknown) => { const code = (e as { code?: string }).code; if (code === 'AUTHORITY_REVOKED' || code === 'SERVICE_VERSION_CONFLICT') throw new ConflictException(); if (code === 'SCHOOL_LIFECYCLE_DENIED' || code === 'TENANT_LIFECYCLE_DENIED' || code === 'ROUTE_LIFECYCLE_DENIED' || code === 'SERVICE_LIFECYCLE_DENIED') throw new NotFoundException(); if (code === '23503' || code === '23514') throw new BadRequestException(); if (code === '23505') throw new ConflictException(); throw e; }); }
@Injectable()
export class ServicesService {
  constructor(private readonly repository: ServicesRepository, private readonly policy: ServicesAuthorizationPolicy) {}
  async create(context: ServicesAuthorizationContext, body: unknown) { if (!isUuid(context.principal.subject)) throw new NotFoundException(); const input = parseCreate(body); const school = await this.repository.getSchoolContext(input.schoolId); if (!school || school.status !== 'active' || school.tenantStatus !== 'active' || !this.policy.canManage(context, school.tenantId)) throw new NotFoundException(); return persist(() => this.repository.create(input, { actorId: context.principal.subject, correlationId: context.correlationId, requiredRoles: ['school-admin', 'super-admin'] })); }
  async list(context: ServicesAuthorizationContext, schoolId: string) { if (!isUuid(context.principal.subject) || !isUuid(schoolId)) throw new NotFoundException(); const school = await this.repository.getSchoolContext(schoolId); if (!school || school.status !== 'active' || school.tenantStatus !== 'active' || (!this.policy.isSuperAdmin(context) && school.tenantId !== context.principal.tenantId) || !this.policy.canRead(context, school.tenantId)) throw new NotFoundException(); return this.repository.list(schoolId, this.policy.isSuperAdmin(context) ? undefined : context.principal.tenantId); }
  async get(context: ServicesAuthorizationContext, id: string, schoolId: string) { if (!isUuid(context.principal.subject) || !isUuid(id) || !isUuid(schoolId)) throw new NotFoundException(); const row = await this.repository.get(id, schoolId, this.policy.isSuperAdmin(context) ? undefined : context.principal.tenantId); if (!row || !this.policy.canRead(context, row.tenantId)) throw new NotFoundException(); return row; }
  async update(context: ServicesAuthorizationContext, id: string, schoolId: string, body: unknown) { if (!isUuid(context.principal.subject) || !isUuid(id) || !isUuid(schoolId)) throw new NotFoundException(); const current = await this.repository.get(id, schoolId, this.policy.isSuperAdmin(context) ? undefined : context.principal.tenantId); if (!current || !this.policy.canManage(context, current.tenantId)) throw new NotFoundException(); return persist(async () => { const result = await this.repository.update(id, schoolId, parseUpdate(body), { actorId: context.principal.subject, correlationId: context.correlationId, requiredRoles: ['school-admin', 'super-admin'] }); if (!result) throw Object.assign(new Error('SERVICE_VERSION_CONFLICT'), { code: 'SERVICE_VERSION_CONFLICT' }); return result; }); }
}
