import { Inject, Injectable, OnModuleDestroy } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import type { Pool, PoolClient } from 'pg';
import type { AssignmentKind, AssignmentRecord, AssignmentStatus, CreateAssignmentInput, UpdateAssignmentInput } from './assignments.types.js';
export const ASSIGNMENTS_DB = Symbol('ASSIGNMENTS_DB');
export interface AssignmentsAuditContext { readonly actorId: string; readonly correlationId: string; readonly requiredRoles?: readonly string[]; }
type Row = { id:string; tenant_id:string; school_id:string; service_instance_id:string; target_id:string; status:AssignmentStatus; version:number; created_at:Date; updated_at:Date };
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const TABLE: Record<AssignmentKind,string>={driver:'driver_service_assignment',vehicle:'vehicle_service_assignment',student:'student_service_assignment'};
const TARGET: Record<AssignmentKind,string>={driver:'driver_id',vehicle:'vehicle_id',student:'student_id'};
function err(code:string):Error{const e=new Error(code);Object.assign(e,{code});return e;}
function fromRow(row:Row,kind:AssignmentKind):AssignmentRecord{return {id:row.id,kind,tenantId:row.tenant_id,schoolId:row.school_id,serviceInstanceId:row.service_instance_id,targetId:row.target_id,status:row.status,version:row.version,createdAt:row.created_at.toISOString(),updatedAt:row.updated_at.toISOString()};}
@Injectable()
export class AssignmentsRepository implements OnModuleDestroy {
  constructor(@Inject(ASSIGNMENTS_DB) private readonly pool:Pool){}
  private async authority(client:PoolClient,actorId:string,tenantId:string|undefined,roles:readonly string[]):Promise<void>{if(!UUID.test(actorId))throw err('AUTHORITY_REVOKED');const r=await client.query(`SELECT r.role FROM "user" u JOIN tenant_membership m ON m.user_id=u.id AND m.status='active' JOIN role_assignment r ON r.membership_id=m.id AND r.status='active' JOIN tenant t ON t.id=m.tenant_id AND t.status='active' WHERE u.id=$1 AND u.status='active' AND ($2::uuid IS NULL OR m.tenant_id=$2 OR r.role='super-admin') AND r.role=ANY($3::text[]) FOR UPDATE OF u,m,r,t`,[actorId,tenantId??null,roles]);if(!r.rows.length)throw err('AUTHORITY_REVOKED');}
  async assertReadAuthority(actorId:string,tenantId:string|undefined,roles:readonly string[]):Promise<void>{const client=await this.pool.connect();try{await client.query('BEGIN');await this.authority(client,actorId,tenantId,roles);await client.query('COMMIT');}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
  private async audit(client:PoolClient,c:AssignmentsAuditContext,tenantId:string,id:string,kind:AssignmentKind,action:string){await client.query('INSERT INTO audit_record (id,tenant_id,actor_id,actor_type,action,target_type,target_id,outcome,correlation_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)',[randomUUID(),tenantId,c.actorId,'human',`assignment.${kind}.${action}`,'assignment',id,'committed',c.correlationId]);}
  async create(input:CreateAssignmentInput,c:AssignmentsAuditContext):Promise<AssignmentRecord>{const client=await this.pool.connect();const table=TABLE[input.kind],target=TARGET[input.kind];try{await client.query('BEGIN');const scope=await client.query<{tenant_id:string;school_id:string;instance_status:string;tenant_status:string;school_status:string}>(`SELECT si.tenant_id,si.school_id,si.status instance_status,t.status tenant_status,sc.status school_status FROM service_instance si JOIN tenant t ON t.id=si.tenant_id JOIN school sc ON sc.id=si.school_id AND sc.tenant_id=si.tenant_id WHERE si.id=$1 AND si.school_id=$2 FOR UPDATE OF si,t,sc`,[input.serviceInstanceId,input.schoolId]);if(!scope.rows[0])throw err('SCOPE_NOT_FOUND');const s=scope.rows[0];if(s.tenant_status!=='active')throw err('TENANT_LIFECYCLE_DENIED');if(s.school_status!=='active'||s.instance_status!=='active')throw err('LIFECYCLE_DENIED');await this.authority(client,c.actorId,s.tenant_id,c.requiredRoles??['school-admin','super-admin']);const targetTable=input.kind==='driver'?'driver_profile':input.kind==='vehicle'?'vehicle':'student';const targetRow=await client.query(`SELECT id FROM ${targetTable} WHERE id=$1 AND tenant_id=$2 AND status='active'${input.kind==='student'?' AND school_id=$3':''} FOR UPDATE`,input.kind==='student'?[input.targetId,s.tenant_id,s.school_id]:[input.targetId,s.tenant_id]);if(!targetRow.rows.length)throw err('TARGET_NOT_ACTIVE');const result=await client.query<Row>(`INSERT INTO ${table} (id,tenant_id,school_id,service_instance_id,${target}) VALUES ($1,$2,$3,$4,$5) RETURNING id,tenant_id,school_id,service_instance_id,${target} AS target_id,status,version,created_at,updated_at`,[randomUUID(),s.tenant_id,s.school_id,input.serviceInstanceId,input.targetId]);await this.audit(client,c,s.tenant_id,result.rows[0]!.id,input.kind,'create');await client.query('COMMIT');return fromRow(result.rows[0]!,input.kind);}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
  async list(kind:AssignmentKind,tenantId:string|undefined,actorId?:string):Promise<AssignmentRecord[]>{const table=TABLE[kind],target=TARGET[kind];const driverFilter=kind==='driver'&&actorId?` AND EXISTS (SELECT 1 FROM driver_profile dp JOIN "user" du ON du.id=dp.user_id AND du.status='active' WHERE dp.id=a.${target} AND dp.status='active' AND du.id=$2)`:'';const params=driverFilter?[tenantId??null,actorId]:[tenantId??null];const result=await this.pool.query<Row>(`SELECT a.id,a.tenant_id,a.school_id,a.service_instance_id,a.${target} AS target_id,a.status,a.version,a.created_at,a.updated_at FROM ${table} a JOIN tenant t ON t.id=a.tenant_id AND t.status='active' JOIN school sc ON sc.id=a.school_id AND sc.tenant_id=a.tenant_id AND sc.status='active' JOIN service_instance si ON si.id=a.service_instance_id AND si.tenant_id=a.tenant_id AND si.school_id=a.school_id AND si.status='active' WHERE a.status='active' AND ($1::uuid IS NULL OR a.tenant_id=$1)${driverFilter} ORDER BY a.id`,params);return result.rows.map(r=>fromRow(r,kind));}
  async get(kind:AssignmentKind,id:string,tenantId?:string,actorId?:string):Promise<AssignmentRecord|null>{const table=TABLE[kind],target=TARGET[kind];const driverFilter=kind==='driver'&&actorId?` AND EXISTS (SELECT 1 FROM driver_profile dp JOIN "user" du ON du.id=dp.user_id AND du.status='active' WHERE dp.id=a.${target} AND dp.status='active' AND du.id=$3)`:'';const params=driverFilter?[id,tenantId??null,actorId]:[id,tenantId??null];const r=await this.pool.query<Row>(`SELECT a.id,a.tenant_id,a.school_id,a.service_instance_id,a.${target} AS target_id,a.status,a.version,a.created_at,a.updated_at FROM ${table} a JOIN tenant t ON t.id=a.tenant_id AND t.status='active' JOIN school sc ON sc.id=a.school_id AND sc.tenant_id=a.tenant_id AND sc.status='active' JOIN service_instance si ON si.id=a.service_instance_id AND si.tenant_id=a.tenant_id AND si.school_id=a.school_id AND si.status='active' WHERE a.id=$1 AND ($2::uuid IS NULL OR a.tenant_id=$2)${driverFilter}` ,params);return r.rows[0]?fromRow(r.rows[0],kind):null;}
  async update(kind:AssignmentKind,id:string,input:UpdateAssignmentInput,c:AssignmentsAuditContext):Promise<AssignmentRecord|null>{const table=TABLE[kind],target=TARGET[kind];const client=await this.pool.connect();try{await client.query('BEGIN');const current=await client.query<Row>(`SELECT a.id,a.tenant_id,a.school_id,a.service_instance_id,a.${target} AS target_id,a.status,a.version,a.created_at,a.updated_at FROM ${table} a WHERE a.id=$1 FOR UPDATE`,[id]);if(!current.rows[0]){await client.query('ROLLBACK');return null;}const row=current.rows[0]!;const instance=await client.query<{status:string;tenant_status:string;school_status:string}>(`SELECT si.status,t.status tenant_status,sc.status school_status FROM service_instance si JOIN tenant t ON t.id=si.tenant_id JOIN school sc ON sc.id=si.school_id AND sc.tenant_id=si.tenant_id WHERE si.id=$1 AND si.tenant_id=$2 AND si.school_id=$3 FOR UPDATE OF si,t,sc`,[row.service_instance_id,row.tenant_id,row.school_id]);if(!instance.rows[0]||instance.rows[0].tenant_status!=='active'||instance.rows[0].school_status!=='active'||(input.status==='active'&&instance.rows[0].status!=='active'))throw err('LIFECYCLE_DENIED');await this.authority(client,c.actorId,row.tenant_id,c.requiredRoles??['school-admin','super-admin']);const targetTable=kind==='driver'?'driver_profile':kind==='vehicle'?'vehicle':'student';const targetRow=await client.query(`SELECT id FROM ${targetTable} WHERE id=$1 AND tenant_id=$2 AND status='active'${kind==='student'?' AND school_id=$3':''} FOR UPDATE`,kind==='student'?[row.target_id,row.tenant_id,row.school_id]:[row.target_id,row.tenant_id]);if(input.status==='active'&&!targetRow.rows.length)throw err('TARGET_NOT_ACTIVE');const result=await client.query<Row>(`UPDATE ${table} SET status=$2,version=version+1,updated_at=NOW() WHERE id=$1 AND version=$3 RETURNING id,tenant_id,school_id,service_instance_id,${target} AS target_id,status,version,created_at,updated_at`,[id,input.status,input.version]);if(!result.rows[0]){await client.query('ROLLBACK');return null;}await this.audit(client,c,row.tenant_id,id,kind,'update');await client.query('COMMIT');return fromRow(result.rows[0]!,kind);}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
  async onModuleDestroy(){await this.pool.end();}
}
