import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { AssignmentsRepository } from './assignments.repository.js';
import { AssignmentsAuthorizationPolicy, type AssignmentsAuthorizationContext } from './assignments.policy.js';
import { isStatus, isUuid, type AssignmentKind, type CreateAssignmentInput, type UpdateAssignmentInput } from './assignments.types.js';
function parseCreate(kind:AssignmentKind,body:unknown):CreateAssignmentInput{const v=(body??{}) as Record<string,unknown>;const allowed=['school_id','service_instance_id',`${kind}_id`];const target=v[`${kind}_id`];if(Object.keys(v).some(k=>!allowed.includes(k))||!isUuid(v.school_id)||!isUuid(v.service_instance_id)||!isUuid(target))throw new BadRequestException();return {kind,schoolId:v.school_id,serviceInstanceId:v.service_instance_id,targetId:target};}
function parseUpdate(body:unknown):UpdateAssignmentInput{const v=(body??{}) as Record<string,unknown>;if(Object.keys(v).some(k=>!['status','version'].includes(k))||!isStatus(v.status)||!Number.isInteger(v.version)||Number(v.version)<1)throw new BadRequestException();return {status:v.status,version:Number(v.version)};}
function persist<T>(op:()=>Promise<T>):Promise<T>{return op().catch((e:unknown)=>{const code=(e as {code?:string}).code;if(code==='AUTHORITY_REVOKED'||code==='ASSIGNMENT_VERSION_CONFLICT'||code==='23505')throw new ConflictException();if(['SCOPE_NOT_FOUND','TENANT_LIFECYCLE_DENIED','LIFECYCLE_DENIED','TARGET_NOT_ACTIVE'].includes(code??'')||code==='23503')throw new NotFoundException();throw e;});}
@Injectable()
export class AssignmentsService{constructor(private readonly repo:AssignmentsRepository,private readonly policy:AssignmentsAuthorizationPolicy){}
  async create(c:AssignmentsAuthorizationContext,kind:AssignmentKind,body:unknown){if(!isUuid(c.principal.subject)||!this.policy.isSchoolAdmin(c)&&!this.policy.isSuperAdmin(c))throw new NotFoundException();const input=parseCreate(kind,body);if(c.principal.tenantId&&!this.policy.isSuperAdmin(c)&&!this.policy.canManage(c,c.principal.tenantId))throw new NotFoundException();return persist(()=>this.repo.create(input,{actorId:c.principal.subject,correlationId:c.correlationId,requiredRoles:['school-admin','super-admin']}));}
  async list(c:AssignmentsAuthorizationContext,kind:AssignmentKind,tenantId?:string){if(!isUuid(c.principal.subject)||(tenantId&&!isUuid(tenantId)))throw new NotFoundException();if(this.policy.isDriver(c)&&kind!=='driver')throw new NotFoundException();if(!this.policy.isSuperAdmin(c)&&tenantId&&tenantId!==c.principal.tenantId)throw new NotFoundException();const rows=await this.repo.list(kind,this.policy.isSuperAdmin(c)?tenantId:c.principal.tenantId,this.policy.isDriver(c)?c.principal.subject:undefined);if(rows.length&&!this.policy.canRead(c,rows[0]!.tenantId))throw new NotFoundException();return rows;}
  async get(c:AssignmentsAuthorizationContext,kind:AssignmentKind,id:string){if(!isUuid(c.principal.subject)||!isUuid(id))throw new NotFoundException();const row=await this.repo.get(kind,id,this.policy.isSuperAdmin(c)?undefined:c.principal.tenantId);if(!row||!this.policy.canRead(c,row.tenantId))throw new NotFoundException();return row;}
  async update(c:AssignmentsAuthorizationContext,kind:AssignmentKind,id:string,body:unknown){if(!isUuid(c.principal.subject)||!isUuid(id)||!this.policy.isSchoolAdmin(c)&&!this.policy.isSuperAdmin(c))throw new NotFoundException();const current=await this.repo.get(kind,id,this.policy.isSuperAdmin(c)?undefined:c.principal.tenantId);if(!current||!this.policy.canManage(c,current.tenantId))throw new NotFoundException();return persist(async()=>{const out=await this.repo.update(kind,id,parseUpdate(body),{actorId:c.principal.subject,correlationId:c.correlationId,requiredRoles:['school-admin','super-admin']});if(!out)throw Object.assign(new Error('ASSIGNMENT_VERSION_CONFLICT'),{code:'ASSIGNMENT_VERSION_CONFLICT'});return out;});}
}
