import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { DriversRepository } from './drivers.repository.js';
import { DriversAuthorizationPolicy, type DriversAuthorizationContext } from './drivers.policy.js';
import { isDriverStatus, isUuid, type CreateDriverInput, type UpdateDriverInput } from './drivers.types.js';

function keys(body: Record<string, unknown>, allowed: readonly string[]): void { if (Object.keys(body).some((key) => !allowed.includes(key))) throw new BadRequestException(); }
function createInput(body: unknown): CreateDriverInput { const value = (body ?? {}) as Record<string, unknown>; keys(value, ['tenant_id', 'user_id']); if (!isUuid(value.tenant_id) || !isUuid(value.user_id)) throw new BadRequestException(); return { tenantId: value.tenant_id, userId: value.user_id }; }
function updateInput(body: unknown): UpdateDriverInput { const value = (body ?? {}) as Record<string, unknown>; keys(value, ['status', 'version']); if (!Number.isInteger(value.version) || Number(value.version) < 1 || !isDriverStatus(value.status)) throw new BadRequestException(); return { status: value.status, version: Number(value.version) }; }
function persist<T>(operation: () => Promise<T>): Promise<T> { return operation().catch((e: unknown) => { const code = (e as { code?: string }).code; if (code === 'AUTHORITY_REVOKED') throw new ConflictException(); if (code === 'DRIVER_VERSION_CONFLICT') throw new ConflictException(); if (['TENANT_LIFECYCLE_DENIED', 'USER_NOT_ACTIVE_DRIVER'].includes(code ?? '')) throw new NotFoundException(); if (code === '23505') throw new ConflictException(); if (code === '23503' || code === '23514') throw new BadRequestException(); throw e; }); }

@Injectable()
export class DriversService {
  constructor(private readonly repository: DriversRepository, private readonly policy: DriversAuthorizationPolicy) {}
  async create(context: DriversAuthorizationContext, body: unknown) { const input = createInput(body); if (!this.policy.canManage(context, input.tenantId)) throw new NotFoundException(); return persist(() => this.repository.create(input, { actorId: context.principal.subject, correlationId: context.correlationId, requiredRoles: ['school-admin', 'super-admin'] })); }
  async list(context: DriversAuthorizationContext, tenantId?: string) { if (tenantId && !isUuid(tenantId)) throw new BadRequestException(); if (!this.policy.isSuperAdmin(context) && (!context.principal.tenantId || (tenantId && tenantId !== context.principal.tenantId))) throw new NotFoundException(); const rows = await this.repository.list(this.policy.isSuperAdmin(context) ? tenantId : context.principal.tenantId); if (rows.length && !this.policy.canRead(context, rows[0]!.tenantId)) throw new NotFoundException(); return rows; }
  async get(context: DriversAuthorizationContext, id: string) { if (!isUuid(id)) throw new NotFoundException(); const row = await this.repository.get(id, this.policy.isSuperAdmin(context) ? undefined : context.principal.tenantId); if (!row || !this.policy.canRead(context, row.tenantId)) throw new NotFoundException(); return row; }
  async update(context: DriversAuthorizationContext, id: string, body: unknown) { if (!isUuid(id)) throw new NotFoundException(); const current = await this.repository.get(id, this.policy.isSuperAdmin(context) ? undefined : context.principal.tenantId); if (!current || !this.policy.canManage(context, current.tenantId)) throw new NotFoundException(); return persist(async () => { const result = await this.repository.update(id, updateInput(body), { actorId: context.principal.subject, correlationId: context.correlationId, requiredRoles: ['school-admin', 'super-admin'] }); if (!result) throw Object.assign(new Error('DRIVER_VERSION_CONFLICT'), { code: 'DRIVER_VERSION_CONFLICT' }); return result; }); }
}
