import { Inject, Injectable, OnModuleDestroy } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import type { Pool, PoolClient } from 'pg';
import type { CreateMembershipInput, CreateRoleAssignmentInput, CreateUserInput, MembershipStatus, RoleAssignmentRecord, TenantMembershipRecord, UpdateMembershipInput, UpdateRoleAssignmentInput, UpdateUserInput, UserRecord, UserRole, UserStatus } from './users.types.js';

export const USERS_DB = Symbol('USERS_DB');
export interface UsersAuditContext { readonly actorId: string; readonly correlationId: string; readonly requiredRoles?: readonly UserRole[]; }
export interface ActorAuthority { readonly tenantId: string; readonly role: UserRole; }
type UserRow = { id: string; email: string; display_name: string; status: UserStatus; version: number; created_at: Date; updated_at: Date };
type MembershipRow = { id: string; user_id: string; tenant_id: string; status: MembershipStatus; version: number; created_at: Date; updated_at: Date };
type RoleRow = { id: string; membership_id: string; role: UserRole; status: MembershipStatus; version: number; created_at: Date; updated_at: Date; tenant_id?: string };

function userFromRow(row: UserRow): UserRecord { return { id: row.id, email: row.email, displayName: row.display_name, status: row.status, version: row.version, createdAt: row.created_at.toISOString(), updatedAt: row.updated_at.toISOString() }; }
function membershipFromRow(row: MembershipRow): TenantMembershipRecord { return { id: row.id, userId: row.user_id, tenantId: row.tenant_id, status: row.status, version: row.version, createdAt: row.created_at.toISOString(), updatedAt: row.updated_at.toISOString() }; }
function roleFromRow(row: RoleRow): RoleAssignmentRecord { return { id: row.id, membershipId: row.membership_id, role: row.role, status: row.status, version: row.version, createdAt: row.created_at.toISOString(), updatedAt: row.updated_at.toISOString() }; }
const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

@Injectable()
export class UsersRepository implements OnModuleDestroy {
  constructor(@Inject(USERS_DB) private readonly pool: Pool) {}
  private async lockActorAuthority(client: PoolClient, actorId: string, tenantId?: string, requiredRoles?: readonly UserRole[]): Promise<void> {
    if (!UUID_PATTERN.test(actorId)) return;
    const result = await client.query<{ role: UserRole }>(`SELECT r.role FROM "user" u JOIN tenant_membership m ON m.user_id = u.id AND m.status = 'active' JOIN role_assignment r ON r.membership_id = m.id AND r.status = 'active' JOIN tenant t ON t.id = m.tenant_id AND t.status = 'active' WHERE u.id = $1 AND u.status = 'active' AND ($2::uuid IS NULL OR m.tenant_id = $2 OR r.role = 'super-admin') AND ($3::text[] IS NULL OR r.role = ANY($3::text[])) FOR UPDATE OF u, m, r, t`, [actorId, tenantId ?? null, requiredRoles ?? null]);
    if (!result.rows.length) { const error = new Error('AUTHORITY_REVOKED'); Object.assign(error, { code: 'AUTHORITY_REVOKED' }); throw error; }
  }
  async getActorAuthorities(subject: string, tenantScope?: string): Promise<ActorAuthority[]> { const result = await this.pool.query<ActorAuthority>('SELECT m.tenant_id AS "tenantId", r.role FROM "user" u JOIN tenant_membership m ON m.user_id = u.id AND m.status = \'active\' JOIN role_assignment r ON r.membership_id = m.id AND r.status = \'active\' JOIN tenant t ON t.id = m.tenant_id AND t.status = \'active\' WHERE u.id = $1 AND u.status = \'active\' AND ($2::uuid IS NULL OR m.tenant_id = $2)', [subject, tenantScope ?? null]); return result.rows; }
  async isTenantActive(tenantId: string): Promise<boolean> { const result = await this.pool.query<{ status: string }>('SELECT status FROM tenant WHERE id = $1', [tenantId]); return result.rows[0]?.status === 'active'; }
  private async audit(client: PoolClient, context: UsersAuditContext, tenantId: string | null, targetType: string, targetId: string, action: string, outcome = 'committed'): Promise<void> {
    await client.query('INSERT INTO audit_record (id, tenant_id, actor_id, actor_type, action, target_type, target_id, outcome, correlation_id) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)', [randomUUID(), tenantId, context.actorId, 'human', action, targetType, targetId, outcome, context.correlationId]);
  }
  async createUser(input: CreateUserInput, context: UsersAuditContext): Promise<UserRecord> { const client = await this.pool.connect(); const id = randomUUID(); try { await client.query('BEGIN'); await this.lockActorAuthority(client, context.actorId, undefined, context.requiredRoles); const result = await client.query<UserRow>('INSERT INTO "user" (id, email, display_name) VALUES ($1, $2, $3) RETURNING id, email, display_name, status, version, created_at, updated_at', [id, input.email, input.displayName]); await this.audit(client, context, null, 'user', id, 'user.create'); await client.query('COMMIT'); return userFromRow(result.rows[0]!); } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); } }
  async getUserIdentity(id: string): Promise<UserRecord | null> { const result = await this.pool.query<UserRow>('SELECT id, email, display_name, status, version, created_at, updated_at FROM "user" WHERE id = $1', [id]); return result.rows[0] ? userFromRow(result.rows[0]) : null; }
  async getUser(id: string, tenantScope?: string): Promise<(UserRecord & { tenantId: string }) | null> { const result = await this.pool.query<UserRow & { tenant_id: string }>('SELECT u.id, u.email, u.display_name, u.status, u.version, u.created_at, u.updated_at, m.tenant_id FROM "user" u JOIN tenant_membership m ON m.user_id = u.id AND m.status = \'active\' JOIN tenant t ON t.id = m.tenant_id WHERE u.id = $1 AND ($2::uuid IS NULL OR (m.tenant_id = $2 AND t.status = \'active\')) ORDER BY m.tenant_id LIMIT 1', [id, tenantScope ?? null]); return result.rows[0] ? { ...userFromRow(result.rows[0]), tenantId: result.rows[0].tenant_id } : null; }
  async listUsers(tenantScope?: string): Promise<Array<UserRecord & { tenantId: string }>> { const result = await this.pool.query<UserRow & { tenant_id: string }>('SELECT DISTINCT ON (u.id) u.id, u.email, u.display_name, u.status, u.version, u.created_at, u.updated_at, m.tenant_id FROM "user" u JOIN tenant_membership m ON m.user_id = u.id AND m.status = \'active\' JOIN tenant t ON t.id = m.tenant_id WHERE u.status = \'active\' AND ($1::uuid IS NULL OR (m.tenant_id = $1 AND t.status = \'active\')) ORDER BY u.id, m.tenant_id', [tenantScope ?? null]); return result.rows.map((row) => ({ ...userFromRow(row), tenantId: row.tenant_id })); }
  async updateUser(id: string, input: UpdateUserInput, context: UsersAuditContext, tenantScope?: string): Promise<(UserRecord & { tenantId: string }) | null> { const client = await this.pool.connect(); try { await client.query('BEGIN'); await this.lockActorAuthority(client, context.actorId, tenantScope, context.requiredRoles); const current = await client.query<{ tenant_id: string }>('SELECT m.tenant_id FROM tenant_membership m WHERE m.user_id = $1 AND m.status = \'active\' AND ($2::uuid IS NULL OR m.tenant_id = $2) ORDER BY m.tenant_id LIMIT 1 FOR UPDATE', [id, tenantScope ?? null]); if (!current.rows[0]) { await client.query('ROLLBACK'); return null; } const result = await client.query<UserRow>('UPDATE "user" SET display_name = COALESCE($2, display_name), status = COALESCE($3, status), version = version + 1, updated_at = NOW() WHERE id = $1 AND version = $4 RETURNING id, email, display_name, status, version, created_at, updated_at', [id, input.displayName ?? null, input.status ?? null, input.version]); if (!result.rows[0]) { await client.query('ROLLBACK'); return null; } await this.audit(client, context, current.rows[0].tenant_id, 'user', id, 'user.update'); await client.query('COMMIT'); return { ...userFromRow(result.rows[0]), tenantId: current.rows[0].tenant_id }; } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); } }
  async createMembership(input: CreateMembershipInput, context: UsersAuditContext): Promise<TenantMembershipRecord> { const client = await this.pool.connect(); const id = randomUUID(); try { await client.query('BEGIN'); await this.lockActorAuthority(client, context.actorId, input.tenantId, context.requiredRoles); const tenant = await client.query<{ status: string }>('SELECT status FROM tenant WHERE id = $1 FOR UPDATE', [input.tenantId]); if (!tenant.rows[0] || tenant.rows[0].status !== 'active') { const error = new Error('TENANT_LIFECYCLE_DENIED'); Object.assign(error, { code: 'TENANT_LIFECYCLE_DENIED' }); throw error; } const result = await client.query<MembershipRow>('INSERT INTO tenant_membership (id, user_id, tenant_id) VALUES ($1, $2, $3) RETURNING id, user_id, tenant_id, status, version, created_at, updated_at', [id, input.userId, input.tenantId]); await this.audit(client, context, input.tenantId, 'tenant_membership', id, 'membership.create'); await client.query('COMMIT'); return membershipFromRow(result.rows[0]!); } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); } }
  async getMembership(id: string, tenantScope?: string): Promise<TenantMembershipRecord | null> { const result = await this.pool.query<MembershipRow>('SELECT m.id, m.user_id, m.tenant_id, m.status, m.version, m.created_at, m.updated_at FROM tenant_membership m JOIN tenant t ON t.id = m.tenant_id WHERE m.id = $1 AND ($2::uuid IS NULL OR (m.tenant_id = $2 AND t.status = \'active\'))', [id, tenantScope ?? null]); return result.rows[0] ? membershipFromRow(result.rows[0]) : null; }
  async listMemberships(tenantScope?: string): Promise<TenantMembershipRecord[]> { const result = await this.pool.query<MembershipRow>('SELECT m.id, m.user_id, m.tenant_id, m.status, m.version, m.created_at, m.updated_at FROM tenant_membership m JOIN tenant t ON t.id = m.tenant_id WHERE ($1::uuid IS NULL OR (m.tenant_id = $1 AND t.status = \'active\')) ORDER BY m.id', [tenantScope ?? null]); return result.rows.map(membershipFromRow); }
  async updateMembership(id: string, input: UpdateMembershipInput, context: UsersAuditContext, tenantScope?: string): Promise<TenantMembershipRecord | null> { const client = await this.pool.connect(); try { await client.query('BEGIN'); await this.lockActorAuthority(client, context.actorId, tenantScope, context.requiredRoles); const current = await client.query<{ tenant_id: string; tenant_status: string; user_status: UserStatus }>('SELECT m.tenant_id, t.status AS tenant_status, u.status AS user_status FROM tenant_membership m JOIN tenant t ON t.id = m.tenant_id JOIN "user" u ON u.id = m.user_id WHERE m.id = $1 AND ($2::uuid IS NULL OR m.tenant_id = $2) FOR UPDATE', [id, tenantScope ?? null]); if (!current.rows[0] || current.rows[0].tenant_status !== 'active' || current.rows[0].user_status !== 'active') { const error = new Error('TENANT_LIFECYCLE_DENIED'); Object.assign(error, { code: 'TENANT_LIFECYCLE_DENIED' }); throw error; } const result = await client.query<MembershipRow>('UPDATE tenant_membership SET status = $2, version = version + 1, updated_at = NOW() WHERE id = $1 AND version = $3 RETURNING id, user_id, tenant_id, status, version, created_at, updated_at', [id, input.status, input.version]); if (!result.rows[0]) { await client.query('ROLLBACK'); return null; } await this.audit(client, context, result.rows[0].tenant_id, 'tenant_membership', id, 'membership.update'); await client.query('COMMIT'); return membershipFromRow(result.rows[0]); } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); } }
  async createRoleAssignment(input: CreateRoleAssignmentInput, context: UsersAuditContext): Promise<RoleAssignmentRecord> { const client = await this.pool.connect(); const id = randomUUID(); try { await client.query('BEGIN'); await this.lockActorAuthority(client, context.actorId, undefined, context.requiredRoles); const membership = await client.query<{ tenant_id: string; status: MembershipStatus; tenant_status: string }>('SELECT m.tenant_id, m.status, t.status AS tenant_status FROM tenant_membership m JOIN tenant t ON t.id = m.tenant_id WHERE m.id = $1 FOR UPDATE', [input.membershipId]); if (!membership.rows[0] || membership.rows[0].status !== 'active' || membership.rows[0].tenant_status !== 'active') { const error = new Error('MEMBERSHIP_INACTIVE'); Object.assign(error, { code: 'MEMBERSHIP_INACTIVE' }); throw error; } const result = await client.query<RoleRow>('INSERT INTO role_assignment (id, membership_id, role) VALUES ($1, $2, $3) RETURNING id, membership_id, role, status, version, created_at, updated_at', [id, input.membershipId, input.role]); await this.audit(client, context, membership.rows[0].tenant_id, 'role_assignment', id, 'role.create'); await client.query('COMMIT'); return roleFromRow(result.rows[0]!); } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); } }
  async getRoleAssignment(id: string, tenantScope?: string): Promise<(RoleAssignmentRecord & { tenantId: string }) | null> { const result = await this.pool.query<RoleRow>('SELECT r.id, r.membership_id, r.role, r.status, r.version, r.created_at, r.updated_at, m.tenant_id FROM role_assignment r JOIN tenant_membership m ON m.id = r.membership_id JOIN tenant t ON t.id = m.tenant_id WHERE r.id = $1 AND m.status = \'active\' AND ($2::uuid IS NULL OR (m.tenant_id = $2 AND t.status = \'active\'))', [id, tenantScope ?? null]); return result.rows[0] ? { ...roleFromRow(result.rows[0]), tenantId: result.rows[0].tenant_id! } : null; }
  async listRoleAssignments(tenantScope?: string): Promise<Array<RoleAssignmentRecord & { tenantId: string }>> { const result = await this.pool.query<RoleRow>('SELECT r.id, r.membership_id, r.role, r.status, r.version, r.created_at, r.updated_at, m.tenant_id FROM role_assignment r JOIN tenant_membership m ON m.id = r.membership_id JOIN tenant t ON t.id = m.tenant_id WHERE m.status = \'active\' AND ($1::uuid IS NULL OR (m.tenant_id = $1 AND t.status = \'active\')) ORDER BY r.id', [tenantScope ?? null]); return result.rows.map((row) => ({ ...roleFromRow(row), tenantId: row.tenant_id! })); }
  async updateRoleAssignment(id: string, input: UpdateRoleAssignmentInput, context: UsersAuditContext, tenantScope?: string): Promise<(RoleAssignmentRecord & { tenantId: string }) | null> { const client = await this.pool.connect(); try { await client.query('BEGIN'); await this.lockActorAuthority(client, context.actorId, tenantScope, context.requiredRoles); const current = await client.query<{ tenant_id: string; membership_status: MembershipStatus; tenant_status: string }>('SELECT m.tenant_id, m.status AS membership_status, t.status AS tenant_status FROM tenant_membership m JOIN tenant t ON t.id = m.tenant_id JOIN role_assignment r ON r.membership_id = m.id WHERE r.id = $1 AND ($2::uuid IS NULL OR m.tenant_id = $2) FOR UPDATE OF m, r', [id, tenantScope ?? null]); if (!current.rows[0] || current.rows[0].membership_status !== 'active' || current.rows[0].tenant_status !== 'active') { const error = new Error('MEMBERSHIP_INACTIVE'); Object.assign(error, { code: 'MEMBERSHIP_INACTIVE' }); throw error; } const result = await client.query<RoleRow>('UPDATE role_assignment SET role = COALESCE($2, role), status = COALESCE($3, status), version = version + 1 WHERE id = $1 AND version = $4 RETURNING id, membership_id, role, status, version, created_at, updated_at, (SELECT m.tenant_id FROM tenant_membership m WHERE m.id = membership_id) AS tenant_id', [id, input.role ?? null, input.status ?? null, input.version]); if (!result.rows[0]) { await client.query('ROLLBACK'); return null; } await this.audit(client, context, result.rows[0].tenant_id!, 'role_assignment', id, 'role.update'); await client.query('COMMIT'); return { ...roleFromRow(result.rows[0]), tenantId: result.rows[0].tenant_id! }; } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); } }
  async onModuleDestroy(): Promise<void> { await this.pool.end(); }
}
