import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { UsersAuthorizationPolicy, type UsersAuthorizationContext } from './users.policy.js';
import { UsersRepository } from './users.repository.js';
import { isMembershipStatus, isUserRole, isUserStatus, isUuid, validateDisplayName, validateEmail, type CreateMembershipInput, type CreateRoleAssignmentInput, type CreateUserInput, type UpdateMembershipInput, type UpdateRoleAssignmentInput, type UpdateUserInput } from './users.types.js';

function keys(body: unknown, allowed: readonly string[]): Record<string, unknown> { const value = (body ?? {}) as Record<string, unknown>; if (!value || typeof value !== 'object' || Object.keys(value).some((key) => !allowed.includes(key))) throw new BadRequestException(); return value; }
function version(value: unknown): number { if (!Number.isInteger(value) || (value as number) < 1) throw new BadRequestException(); return value as number; }
function parseCreateUser(body: unknown): CreateUserInput { const value = keys(body, ['email', 'display_name']); return { email: validateEmail(value.email), displayName: validateDisplayName(value.display_name) }; }
function parseUpdateUser(body: unknown): UpdateUserInput { const value = keys(body, ['display_name', 'status', 'version']); if (value.display_name === undefined && value.status === undefined) throw new BadRequestException(); if (value.status !== undefined && !isUserStatus(value.status)) throw new BadRequestException(); return { displayName: value.display_name === undefined ? undefined : validateDisplayName(value.display_name), status: value.status as UpdateUserInput['status'], version: version(value.version) }; }
function parseCreateMembership(body: unknown): CreateMembershipInput { const value = keys(body, ['user_id', 'tenant_id']); if (!isUuid(value.user_id) || !isUuid(value.tenant_id)) throw new BadRequestException(); return { userId: value.user_id, tenantId: value.tenant_id }; }
function parseUpdateMembership(body: unknown): UpdateMembershipInput { const value = keys(body, ['status', 'version']); if (value.status === undefined || !isMembershipStatus(value.status)) throw new BadRequestException(); return { status: value.status, version: version(value.version) }; }
function parseCreateRole(body: unknown): CreateRoleAssignmentInput { const value = keys(body, ['membership_id', 'role']); if (!isUuid(value.membership_id) || !isUserRole(value.role)) throw new BadRequestException(); return { membershipId: value.membership_id, role: value.role }; }
function parseUpdateRole(body: unknown): UpdateRoleAssignmentInput { const value = keys(body, ['role', 'status', 'version']); if (value.role === undefined && value.status === undefined) throw new BadRequestException(); if (value.role !== undefined && !isUserRole(value.role)) throw new BadRequestException(); if (value.status !== undefined && !isMembershipStatus(value.status)) throw new BadRequestException(); return { role: value.role as UpdateRoleAssignmentInput['role'], status: value.status as UpdateRoleAssignmentInput['status'], version: version(value.version) }; }
async function persist<T>(operation: () => Promise<T>): Promise<T> { try { return await operation(); } catch (error) { const code = (error as { code?: string }).code; if (code === '23505') throw new ConflictException(); if (code === '23503' || code === '23514') throw new BadRequestException(); if (code === 'MEMBERSHIP_INACTIVE' || code === 'AUTHORITY_REVOKED') throw new ConflictException(); if (code === 'TENANT_LIFECYCLE_DENIED') throw new NotFoundException(); throw error; } }

@Injectable()
export class UsersService {
  constructor(private readonly repository: UsersRepository, private readonly policy: UsersAuthorizationPolicy) {}
  private async authorize(context: UsersAuthorizationContext, tenantId?: string): Promise<UsersAuthorizationContext> {
    const authorities = await this.repository.getActorAuthorities(context.principal.subject);
    if (!authorities.length) throw new ForbiddenException();
    const isPlatformAdmin = authorities.some((authority) => authority.role === 'super-admin');
    const scoped = tenantId ?? context.principal.tenantId;
    const effectiveAuthorities = isPlatformAdmin ? authorities : authorities.filter((authority) => !scoped || authority.tenantId === scoped);
    if (!effectiveAuthorities.length) throw new ForbiddenException();
    return { ...context, authoritativeRoles: effectiveAuthorities.map((authority) => authority.role) };
  }
  async createUser(context: UsersAuthorizationContext, body: unknown) { const authorized = await this.authorize(context); if (!this.policy.canManageIdentity(authorized)) throw new ForbiddenException(); return persist(() => this.repository.createUser(parseCreateUser(body), { actorId: context.principal.subject, correlationId: context.correlationId, requiredRoles: ['super-admin'] })); }
  async listUsers(context: UsersAuthorizationContext) { const tenantScope = context.principal.tenantId; const authorized = await this.authorize(context, tenantScope); if (!this.policy.canManageUsers(authorized, tenantScope)) throw new ForbiddenException(); return this.repository.listUsers(this.policy.isSuperAdmin(authorized) ? undefined : tenantScope); }
  async getUser(context: UsersAuthorizationContext, id: string) { if (!isUuid(id)) throw new NotFoundException(); const authorized = await this.authorize(context, context.principal.tenantId); const record = await this.repository.getUser(id, this.policy.tenantScope(authorized)); if (!record || !this.policy.canReadUser(authorized, record.tenantId) || (record.status === 'disabled' && !this.policy.isSuperAdmin(authorized))) throw new NotFoundException(); return record; }
  async updateUser(context: UsersAuthorizationContext, id: string, body: unknown) { if (!isUuid(id)) throw new NotFoundException(); const authorized = await this.authorize(context); if (!this.policy.canManageIdentity(authorized)) throw new ForbiddenException(); const current = await this.repository.getUser(id); if (!current) throw new NotFoundException(); const updated = await persist(() => this.repository.updateUser(id, parseUpdateUser(body), { actorId: context.principal.subject, correlationId: context.correlationId, requiredRoles: ['super-admin'] })); if (!updated) throw new ConflictException(); return updated; }
  async createMembership(context: UsersAuthorizationContext, body: unknown) { const input = parseCreateMembership(body); const authorized = await this.authorize(context, input.tenantId); if (!this.policy.canManageUsers(authorized, input.tenantId)) throw new NotFoundException(); const user = await this.repository.getUserIdentity(input.userId); if (!user || user.status !== 'active') throw new NotFoundException(); return persist(() => this.repository.createMembership(input, { actorId: context.principal.subject, correlationId: context.correlationId, requiredRoles: ['school-admin', 'super-admin'] })); }
  async listMemberships(context: UsersAuthorizationContext) { const authorized = await this.authorize(context, context.principal.tenantId); if (!this.policy.canManageUsers(authorized, context.principal.tenantId)) throw new ForbiddenException(); return this.repository.listMemberships(this.policy.isSuperAdmin(authorized) ? undefined : context.principal.tenantId); }
  async getMembership(context: UsersAuthorizationContext, id: string) { if (!isUuid(id)) throw new NotFoundException(); const authorized = await this.authorize(context); const scope = this.policy.isSuperAdmin(authorized) ? undefined : context.principal.tenantId; const record = await this.repository.getMembership(id, scope); if (!record || !this.policy.canManageUsers(authorized, record.tenantId)) throw new NotFoundException(); return record; }
  async updateMembership(context: UsersAuthorizationContext, id: string, body: unknown) { if (!isUuid(id)) throw new NotFoundException(); const authorized = await this.authorize(context); const scope = this.policy.isSuperAdmin(authorized) ? undefined : context.principal.tenantId; const current = await this.repository.getMembership(id, scope); if (!current || !this.policy.canManageUsers(authorized, current.tenantId)) throw new NotFoundException(); const updated = await persist(() => this.repository.updateMembership(id, parseUpdateMembership(body), { actorId: context.principal.subject, correlationId: context.correlationId, requiredRoles: ['school-admin', 'super-admin'] }, this.policy.isSuperAdmin(authorized) ? undefined : current.tenantId)); if (!updated) throw new ConflictException(); return updated; }
  async createRoleAssignment(context: UsersAuthorizationContext, body: unknown) { const input = parseCreateRole(body); const authorized = await this.authorize(context); const scope = this.policy.isSuperAdmin(authorized) ? undefined : context.principal.tenantId; const membership = await this.repository.getMembership(input.membershipId, scope); if (!membership) throw new NotFoundException(); if (!this.policy.canManageRole(authorized, membership.tenantId, input.role)) throw new NotFoundException(); return persist(() => this.repository.createRoleAssignment(input, { actorId: context.principal.subject, correlationId: context.correlationId, requiredRoles: ['school-admin', 'super-admin'] })); }
  async listRoleAssignments(context: UsersAuthorizationContext) { const authorized = await this.authorize(context, context.principal.tenantId); if (!this.policy.canManageUsers(authorized, context.principal.tenantId)) throw new ForbiddenException(); return this.repository.listRoleAssignments(this.policy.isSuperAdmin(authorized) ? undefined : context.principal.tenantId); }
  async getRoleAssignment(context: UsersAuthorizationContext, id: string) { if (!isUuid(id)) throw new NotFoundException(); const authorized = await this.authorize(context); const scope = this.policy.isSuperAdmin(authorized) ? undefined : context.principal.tenantId; const record = await this.repository.getRoleAssignment(id, scope); if (!record || !this.policy.canManageUsers(authorized, record.tenantId)) throw new NotFoundException(); return record; }
  async updateRoleAssignment(context: UsersAuthorizationContext, id: string, body: unknown) { if (!isUuid(id)) throw new NotFoundException(); const authorized = await this.authorize(context); const scope = this.policy.isSuperAdmin(authorized) ? undefined : context.principal.tenantId; const current = await this.repository.getRoleAssignment(id, scope); const input = parseUpdateRole(body); if (!current) throw new NotFoundException(); if (!this.policy.canManageRole(authorized, current.tenantId, input.role ?? current.role)) throw new NotFoundException(); const updated = await persist(() => this.repository.updateRoleAssignment(id, input, { actorId: context.principal.subject, correlationId: context.correlationId, requiredRoles: ['school-admin', 'super-admin'] }, this.policy.isSuperAdmin(authorized) ? undefined : current.tenantId)); if (!updated) throw new ConflictException(); return updated; }
}
