import { INestApplication, UnauthorizedException } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import { Pool } from 'pg';
import { randomUUID } from 'node:crypto';
import request from 'supertest';
import { AppModule } from '../src/app.module.js';
import { AuthService } from '../src/auth/auth.service.js';
import { CREDENTIAL_VERIFIER, IDENTITY_STATUS_VERIFIER } from '../src/auth/auth.types.js';
import { ApiExceptionFilter } from '../src/common/api-exception.filter.js';
import { correlationMiddleware } from '../src/common/correlation.js';
import { UsersRepository } from '../src/users/users.repository.js';

describe('Parents relationship-bound surface', () => {
  let app: INestApplication; let pool: Pool; let auth: AuthService;
  let tenantId: string; let schoolId: string; let studentId: string; let adminId: string; let parentId: string; let guardianId: string;
  async function token(subject: string, roles: string[], tenantId?: string): Promise<string> { return auth.issueForTestOnly({ subject, roles, tenantId }); }
  async function actor(role: string): Promise<string> { const id=randomUUID(); await pool.query('INSERT INTO "user" (id,email,display_name) VALUES ($1,$2,$3)',[id,`parent-${id}@example.test`,role]); const m=await pool.query<{id:string}>('INSERT INTO tenant_membership(id,user_id,tenant_id) VALUES($1,$2,$3) RETURNING id',[randomUUID(),id,tenantId]); await pool.query('INSERT INTO role_assignment(id,membership_id,role) VALUES($1,$2,$3)',[randomUUID(),m.rows[0]!.id,role]); return id; }
  beforeAll(async()=>{ if(!process.env.DATABASE_URL) throw new Error('DATABASE_URL_REQUIRED_FOR_PARENTS_TEST'); process.env.AUTH_PROVISIONAL_SIGNING_SECRET='test-secret-that-is-at-least-thirty-two-chars'; pool=new Pool({connectionString:process.env.DATABASE_URL}); const mod=await Test.createTestingModule({imports:[AppModule]}).overrideProvider(CREDENTIAL_VERIFIER).useValue({verify:async()=>null}).overrideProvider(IDENTITY_STATUS_VERIFIER).useFactory({inject:[UsersRepository],factory:(users:UsersRepository)=>({assertActive:async(p:{subject:string;tenantId?:string;roles:string[]})=>{if(!/^[0-9a-f-]{36}$/i.test(p.subject))return p;const a=await users.getActorAuthorities(p.subject);if(!a.filter(x=>!p.tenantId||x.tenantId===p.tenantId||x.role==='super-admin').length)throw new UnauthorizedException();return p;}})}).compile(); app=mod.createNestApplication();app.use(correlationMiddleware);app.useGlobalFilters(new ApiExceptionFilter());await app.init();auth=app.get(AuthService);
    const bootstrap=await token('parents-bootstrap',['super-admin']); const tenant=await request(app.getHttpServer()).post('/tenants').set('Authorization',`Bearer ${bootstrap}`).send({name:`Parents Tenant ${Date.now()}`});expect(tenant.status).toBe(201);tenantId=tenant.body.id; const school=await request(app.getHttpServer()).post('/schools').set('Authorization',`Bearer ${bootstrap}`).send({tenant_id:tenantId,name:'Parents School'});expect(school.status).toBe(201);schoolId=school.body.id; adminId=await actor('school-admin'); parentId=await actor('parent'); const st=await request(app.getHttpServer()).post('/students').set('Authorization',`Bearer ${await token(adminId,['school-admin'],tenantId)}`).send({school_id:schoolId,display_name:'Linked Child'});expect(st.status).toBe(201);studentId=st.body.id; });
  afterAll(async()=>{await app?.close();if(pool){await pool.query('DELETE FROM student_guardian_relationship WHERE tenant_id=$1',[tenantId]);await pool.query('DELETE FROM guardian WHERE tenant_id=$1',[tenantId]);await pool.query('DELETE FROM student WHERE tenant_id=$1',[tenantId]);await pool.query('DELETE FROM role_assignment WHERE membership_id IN (SELECT id FROM tenant_membership WHERE tenant_id=$1)',[tenantId]);await pool.query('DELETE FROM tenant_membership WHERE tenant_id=$1',[tenantId]);await pool.query('DELETE FROM "user" WHERE email LIKE \'parent-%@example.test\'');await pool.query('DELETE FROM school WHERE id=$1',[schoolId]);await pool.query('DELETE FROM tenant WHERE id=$1',[tenantId]);await pool.end();}});
  it('creates an explicit relationship and limits parent reads to linked active children',async()=>{const admin=await token(adminId,['school-admin'],tenantId);const parent=await token(parentId,['parent'],tenantId);const g=await request(app.getHttpServer()).post('/guardians').set('Authorization',`Bearer ${admin}`).send({tenant_id:tenantId,user_id:parentId});expect(g.status).toBe(201);guardianId=g.body.id;const link=await request(app.getHttpServer()).post('/student-guardian-relationships').set('Authorization',`Bearer ${admin}`).send({guardian_id:guardianId,student_id:studentId});expect(link.status).toBe(201);const children=await request(app.getHttpServer()).get('/me/children').set('Authorization',`Bearer ${parent}`);expect(children.status).toBe(200);expect(children.body).toHaveLength(1);expect(children.body[0].student_id).toBe(studentId);});
  it('denies management to parent actors and hides archived relationships',async()=>{const parent=await token(parentId,['parent'],tenantId);expect((await request(app.getHttpServer()).post('/guardians').set('Authorization',`Bearer ${parent}`).send({tenant_id:tenantId,user_id:parentId})).status).toBe(404);await pool.query("UPDATE guardian SET status='archived',version=version+1 WHERE id=$1",[guardianId]);const children=await request(app.getHttpServer()).get('/me/children').set('Authorization',`Bearer ${parent}`);expect(children.status).toBe(200);expect(children.body).toHaveLength(0);});
});
