import { INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import { Pool } from 'pg';
import { randomUUID } from 'node:crypto';
import request from 'supertest';
import { AppModule } from '../src/app.module.js';
import { AuthService } from '../src/auth/auth.service.js';
import { CREDENTIAL_VERIFIER } from '../src/auth/auth.types.js';
import { ApiExceptionFilter } from '../src/common/api-exception.filter.js';
import { correlationMiddleware } from '../src/common/correlation.js';

describe('Transport service tenant/school/route scoped lifecycle surface', () => {
  let app: INestApplication; let pool: Pool; let auth: AuthService;
  let tenantId: string; let otherTenantId: string; let schoolId: string; let otherSchoolId: string; let routeId: string; let serviceId: string; let adminId: string; let otherAdminId: string; let operatorId: string; let bootstrapTenantId: string; let bootstrapId: string;
  async function token(subject: string, roles: string[], tenant?: string): Promise<string> { return auth.issueForTestOnly({ subject, roles, tenantId: tenant }); }
  async function actor(role: string, tenant: string): Promise<string> { const id = randomUUID(); await pool.query('INSERT INTO "user" (id,email,display_name) VALUES ($1,$2,$3)', [id, `${role}-${id}@services.example.test`, role]); const membership = await pool.query<{ id: string }>('INSERT INTO tenant_membership(id,user_id,tenant_id) VALUES($1,$2,$3) RETURNING id', [randomUUID(), id, tenant]); await pool.query('INSERT INTO role_assignment(id,membership_id,role) VALUES($1,$2,$3)', [randomUUID(), membership.rows[0]!.id, role]); return id; }
  beforeAll(async () => { if (!process.env.DATABASE_URL) throw new Error('DATABASE_URL_REQUIRED_FOR_SERVICES_TEST'); process.env.AUTH_PROVISIONAL_SIGNING_SECRET = 'test-secret-that-is-at-least-thirty-two-chars'; pool = new Pool({ connectionString: process.env.DATABASE_URL }); bootstrapTenantId = randomUUID(); bootstrapId = randomUUID(); await pool.query('INSERT INTO tenant (id,name) VALUES ($1,$2)', [bootstrapTenantId, `Services Bootstrap ${Date.now()}`]); await pool.query('INSERT INTO "user" (id,email,display_name) VALUES ($1,$2,$3)', [bootstrapId, `bootstrap-${bootstrapId}@services.example.test`, 'Services Bootstrap']); const membership = await pool.query<{ id: string }>('INSERT INTO tenant_membership(id,user_id,tenant_id) VALUES($1,$2,$3) RETURNING id', [randomUUID(), bootstrapId, bootstrapTenantId]); await pool.query('INSERT INTO role_assignment(id,membership_id,role) VALUES($1,$2,$3)', [randomUUID(), membership.rows[0]!.id, 'super-admin']); const module = await Test.createTestingModule({ imports: [AppModule] }).overrideProvider(CREDENTIAL_VERIFIER).useValue({ verify: async () => null }).compile(); app = module.createNestApplication(); app.use(correlationMiddleware); app.useGlobalFilters(new ApiExceptionFilter()); await app.init(); auth = app.get(AuthService); const bootstrap = await token(bootstrapId, ['super-admin'], bootstrapTenantId); tenantId = (await request(app.getHttpServer()).post('/tenants').set('Authorization', `Bearer ${bootstrap}`).send({ name: `Services Tenant ${Date.now()}` })).body.id; otherTenantId = (await request(app.getHttpServer()).post('/tenants').set('Authorization', `Bearer ${bootstrap}`).send({ name: `Other Services Tenant ${Date.now()}` })).body.id; schoolId = randomUUID(); otherSchoolId = randomUUID(); await pool.query('INSERT INTO school (id,tenant_id,name) VALUES ($1,$2,$3),($4,$5,$6)', [schoolId, tenantId, 'Services School', otherSchoolId, otherTenantId, 'Other Services School']); adminId = await actor('school-admin', tenantId); otherAdminId = await actor('school-admin', otherTenantId); operatorId = await actor('school-operator', tenantId); const route = await request(app.getHttpServer()).post('/routes').set('Authorization', `Bearer ${await token(adminId, ['school-admin'], tenantId)}`).send({ school_id: schoolId, name: 'Service Route' }); expect(route.status).toBe(201); routeId = route.body.id; });
  afterAll(async () => { await app?.close(); if (pool) { const tenants = [tenantId, otherTenantId, bootstrapTenantId]; await pool.query('DELETE FROM transport_service WHERE tenant_id = ANY($1::uuid[])', [tenants]); await pool.query('DELETE FROM route WHERE tenant_id = ANY($1::uuid[])', [tenants]); await pool.query('DELETE FROM school WHERE tenant_id = ANY($1::uuid[])', [tenants]); await pool.query('DELETE FROM role_assignment WHERE membership_id IN (SELECT id FROM tenant_membership WHERE tenant_id = ANY($1::uuid[]))', [tenants]); await pool.query('DELETE FROM tenant_membership WHERE tenant_id = ANY($1::uuid[])', [tenants]); await pool.query('DELETE FROM "user" WHERE email LIKE ANY($1::text[])', [['%services.example.test', `bootstrap-${bootstrapId}@services.example.test`]]); await pool.query('DELETE FROM tenant WHERE id = ANY($1::uuid[])', [tenants]); await pool.end(); } });
  it('creates and lists a route-bound active service', async () => { const admin = await token(adminId, ['school-admin'], tenantId); const created = await request(app.getHttpServer()).post('/transport-services').set('Authorization', `Bearer ${admin}`).send({ school_id: schoolId, route_id: routeId, name: 'Morning Service' }); expect(created.status).toBe(201); expect(created.body.tenantId).toBe(tenantId); expect(created.body.schoolId).toBe(schoolId); expect(created.body.routeId).toBe(routeId); expect(created.body.status).toBe('active'); serviceId = created.body.id; expect((await request(app.getHttpServer()).get(`/transport-services?school_id=${schoolId}`).set('Authorization', `Bearer ${admin}`)).body.map((row: { id: string }) => row.id)).toContain(serviceId); });
  it('denies foreign scope, operator mutation, and client tenant substitution', async () => { const foreign = await token(otherAdminId, ['school-admin'], otherTenantId); expect((await request(app.getHttpServer()).get(`/transport-services/${serviceId}?school_id=${schoolId}`).set('Authorization', `Bearer ${foreign}`)).status).toBe(404); const operator = await token(operatorId, ['school-operator'], tenantId); expect((await request(app.getHttpServer()).patch(`/transport-services/${serviceId}?school_id=${schoolId}`).set('Authorization', `Bearer ${operator}`).send({ name: 'Nope', version: 1 })).status).toBe(404); expect((await request(app.getHttpServer()).post('/transport-services').set('Authorization', `Bearer ${operator}`).send({ school_id: schoolId, route_id: routeId, name: 'Nope', tenant_id: tenantId })).status).toBe(400); });
  it('enforces OCC and archived lifecycle at mutation boundary', async () => { const admin = await token(adminId, ['school-admin'], tenantId); expect((await request(app.getHttpServer()).patch(`/transport-services/${serviceId}?school_id=${schoolId}`).set('Authorization', `Bearer ${admin}`).send({ status: 'archived', version: 99 })).status).toBe(409); const archived = await request(app.getHttpServer()).patch(`/transport-services/${serviceId}?school_id=${schoolId}`).set('Authorization', `Bearer ${admin}`).send({ status: 'archived', version: 1 }); expect(archived.status).toBe(200); expect((await request(app.getHttpServer()).get(`/transport-services/${serviceId}?school_id=${schoolId}`).set('Authorization', `Bearer ${admin}`)).status).toBe(404); expect((await request(app.getHttpServer()).patch(`/transport-services/${serviceId}?school_id=${schoolId}`).set('Authorization', `Bearer ${admin}`).send({ name: 'Archived Mutation', version: 2 })).status).toBe(404); });
});
