import { INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import { Pool } from 'pg';
import { randomUUID } from 'node:crypto';
import request from 'supertest';
import { AppModule } from '../src/app.module.js';
import { AuthService } from '../src/auth/auth.service.js';
import { CREDENTIAL_VERIFIER } from '../src/auth/auth.types.js';
import { ApiExceptionFilter } from '../src/common/api-exception.filter.js';
import { correlationMiddleware } from '../src/common/correlation.js';

describe('Vehicles tenant-scoped lifecycle surface', () => {
  let app: INestApplication; let pool: Pool; let auth: AuthService;
  let tenantId: string; let otherTenantId: string; let adminId: string; let otherAdminId: string; let operatorId: string; let vehicleId: string; let bootstrapTenantId: string; let bootstrapId: string;
  async function token(subject: string, roles: string[], tenant?: string): Promise<string> { return auth.issueForTestOnly({ subject, roles, tenantId: tenant }); }
  async function actor(role: string, tenant: string): Promise<string> { const id = randomUUID(); await pool.query('INSERT INTO "user" (id,email,display_name) VALUES ($1,$2,$3)', [id, `${role}-${id}@vehicles.example.test`, role]); const membership = await pool.query<{ id: string }>('INSERT INTO tenant_membership(id,user_id,tenant_id) VALUES($1,$2,$3) RETURNING id', [randomUUID(), id, tenant]); await pool.query('INSERT INTO role_assignment(id,membership_id,role) VALUES($1,$2,$3)', [randomUUID(), membership.rows[0]!.id, role]); return id; }

  beforeAll(async () => {
    if (!process.env.DATABASE_URL) throw new Error('DATABASE_URL_REQUIRED_FOR_VEHICLES_TEST');
    process.env.AUTH_PROVISIONAL_SIGNING_SECRET = 'test-secret-that-is-at-least-thirty-two-chars'; pool = new Pool({ connectionString: process.env.DATABASE_URL });
    bootstrapTenantId = randomUUID(); bootstrapId = randomUUID(); await pool.query('INSERT INTO tenant (id,name) VALUES ($1,$2)', [bootstrapTenantId, `Vehicles Bootstrap ${Date.now()}`]); await pool.query('INSERT INTO "user" (id,email,display_name) VALUES ($1,$2,$3)', [bootstrapId, `bootstrap-${bootstrapId}@vehicles.example.test`, 'Vehicles Bootstrap']); const bootstrapMembership = await pool.query<{ id: string }>('INSERT INTO tenant_membership(id,user_id,tenant_id) VALUES($1,$2,$3) RETURNING id', [randomUUID(), bootstrapId, bootstrapTenantId]); await pool.query('INSERT INTO role_assignment(id,membership_id,role) VALUES($1,$2,$3)', [randomUUID(), bootstrapMembership.rows[0]!.id, 'super-admin']);
    const module = await Test.createTestingModule({ imports: [AppModule] }).overrideProvider(CREDENTIAL_VERIFIER).useValue({ verify: async () => null }).compile(); app = module.createNestApplication(); app.use(correlationMiddleware); app.useGlobalFilters(new ApiExceptionFilter()); await app.init(); auth = app.get(AuthService);
    const bootstrap = await token(bootstrapId, ['super-admin'], bootstrapTenantId); const tenant = await request(app.getHttpServer()).post('/tenants').set('Authorization', `Bearer ${bootstrap}`).send({ name: `Vehicles Tenant ${Date.now()}` }); expect(tenant.status).toBe(201); tenantId = tenant.body.id; const other = await request(app.getHttpServer()).post('/tenants').set('Authorization', `Bearer ${bootstrap}`).send({ name: `Other Vehicles Tenant ${Date.now()}` }); expect(other.status).toBe(201); otherTenantId = other.body.id; adminId = await actor('school-admin', tenantId); otherAdminId = await actor('school-admin', otherTenantId); operatorId = await actor('school-operator', tenantId);
  });

  afterAll(async () => { await app?.close(); if (pool) { const tenants = [tenantId, otherTenantId, bootstrapTenantId]; await pool.query('DELETE FROM vehicle WHERE tenant_id = ANY($1::uuid[])', [tenants]); await pool.query('DELETE FROM role_assignment WHERE membership_id IN (SELECT id FROM tenant_membership WHERE tenant_id = ANY($1::uuid[]))', [tenants]); await pool.query('DELETE FROM tenant_membership WHERE tenant_id = ANY($1::uuid[])', [tenants]); await pool.query('DELETE FROM "user" WHERE email LIKE ANY($1::text[])', [['%vehicles.example.test', `bootstrap-${bootstrapId}@vehicles.example.test`]]); await pool.query('DELETE FROM tenant WHERE id = ANY($1::uuid[])', [tenants]); await pool.end(); } });

  it('creates and reads an active tenant-scoped Vehicle', async () => { const admin = await token(adminId, ['school-admin'], tenantId); const created = await request(app.getHttpServer()).post('/vehicles').set('Authorization', `Bearer ${admin}`).send({ tenant_id: tenantId, identifier: 'BUS-001' }); expect(created.status).toBe(201); expect(created.body.tenantId).toBe(tenantId); expect(created.body.identifier).toBe('BUS-001'); expect(created.body.status).toBe('active'); vehicleId = created.body.id; const listed = await request(app.getHttpServer()).get('/vehicles').set('Authorization', `Bearer ${admin}`); expect(listed.status).toBe(200); expect(listed.body.map((row: { id: string }) => row.id)).toContain(vehicleId); });
  it('denies cross-tenant access and rejects stale lifecycle updates', async () => { const foreign = await token(otherAdminId, ['school-admin'], otherTenantId); expect((await request(app.getHttpServer()).get(`/vehicles/${vehicleId}`).set('Authorization', `Bearer ${foreign}`)).status).toBe(404); const admin = await token(adminId, ['school-admin'], tenantId); expect((await request(app.getHttpServer()).patch(`/vehicles/${vehicleId}`).set('Authorization', `Bearer ${admin}`).send({ status: 'archived', version: 99 })).status).toBe(409); const archived = await request(app.getHttpServer()).patch(`/vehicles/${vehicleId}`).set('Authorization', `Bearer ${admin}`).send({ status: 'archived', version: 1 }); expect(archived.status).toBe(200); expect((await request(app.getHttpServer()).get(`/vehicles/${vehicleId}`).set('Authorization', `Bearer ${admin}`)).status).toBe(404); });
  it('allows School Operator read access but not mutation or client-owned fields', async () => { const operator = await token(operatorId, ['school-operator'], tenantId); expect((await request(app.getHttpServer()).get('/vehicles').set('Authorization', `Bearer ${operator}`)).status).toBe(200); expect((await request(app.getHttpServer()).post('/vehicles').set('Authorization', `Bearer ${operator}`).send({ tenant_id: tenantId, identifier: 'BUS-OPERATOR' })).status).toBe(404); expect((await request(app.getHttpServer()).post('/vehicles').set('Authorization', `Bearer ${operator}`).send({ tenant_id: tenantId, identifier: 'BUS-EXTRA', status: 'active' })).status).toBe(400); });
  it('denies a previously valid token after actor authority is revoked', async () => { const admin = await token(adminId, ['school-admin'], tenantId); await pool.query("UPDATE role_assignment SET status = 'revoked' WHERE membership_id = (SELECT id FROM tenant_membership WHERE user_id = $1 AND tenant_id = $2) AND role = 'school-admin'", [adminId, tenantId]); expect((await request(app.getHttpServer()).get('/vehicles').set('Authorization', `Bearer ${admin}`)).status).toBe(401); });
});
